### ISSUE TITLE
Password of the google spreadsheet demo file?

### ISSUE THREAD

**Issue by dumblob** [casey/recursive-spreadsheets#1]
The presentation in `index.md` caught my attention and I wonder if I could try what you meant by "recursive" in this context.

Could you provide me either with the password to the demo spreadsheet file or provide the whole file?

**Comment by casey** [comment]
This was sort of a joke presentation on something that I wish was real. The video of the presentation is online:

https://www.youtube.com/watch?v=1WkMpa5zfTA

In short, I wish that you could use spreadsheets to define functions. A spreadsheet that defined a function would have some cells designated as input, and some cells designated as output, and would include formulas that defined the output in terms of the input. They would be recursive in the sense that you would use spreadsheets to define things in spreadsheets. I'll include a link to the presentation in the readme to make this repo make more sense.

**Comment by dumblob** [comment]
Ah, I see. Thanks for the link.

Basically you're saying that you don't want to pass arguments to cells (functions/expressions) only at the receiver side (which is the core idea spreadsheets are built around - i.e. the definition of a function has to include precise specification where the arguments/data come from - from which cell) but have a way to pass arguments at the caller side (as is usual in most programming languages - i.e. allow reuse not by copying but by referencing it by separation of the definition from the actual call).

I actually think it should be possible to write a very simple VBA (ehm :smile:) plugin which would automatically allow a "reuse" of a given definition.

Strictly speaking there could be also a convention how to define such reusable expressions and how to call them even without VBA, but it wouldn't work as people understand spreadsheets as something "free to use however I see fit" and not something to follow yeat another set of rules/constraints/conventions.
